### ISSUE TITLE
ULib Errors with this addon

### ISSUE THREAD

**Issue by snoweuph** [manix84/discord_gmod_addon#6]
when I install the addon I get ulib errors and my game doesn’t work properly, I have already re-installed the server completely and Im using the latest version of ulib. here the logs with and without the add-on and data about the server
[gmodserver-console-noDC.log](https://github.com/manix84/discord_gmod_addon/files/6788329/gmodserver-console-noDC.log)
[gmodserver-console-DC.log](https://github.com/manix84/discord_gmod_addon/files/6788330/gmodserver-console-DC.log)
[server.txt](https://github.com/manix84/discord_gmod_addon/files/6788336/server.txt)

**Comment by NotNorom** [comment]
I am getting the exact same errors.

**Comment by snoweuph** [comment]
You May not know that, but this add-on version is discontinued, the creator is actually working on a v2 if you look into his repositories
